


var tipuesearch = {"pages": [
     
     
     {"title": "Intro", "text": "&amp;#65279;Last April, Generation Rent produceda reportinto the state of Letting Feesin England and Wales.^2 Using the crowdsourcing sitelettingfees.co.uka group of volunteers assembled themost comprehensive picture of letting fees to date - determining not just thetypical fee charged across a number of areas, but categorising individual feesso that we could understand the variation of what was being charged for eachservice. We echoed findings from Shelter^0 and Citizens Advice^1 that letting feesdid not represent a functioning market. The limited power of tenants to shoparound for the cheapest fees meant that there was little incentive for lettingagents to provide a more efficient or cheaper service, resulting a very largerange of possible charges. We argued the solution to this was a ban on lettingfees that would move the cost of fees to landlords - who have a greaterability to choose between rival letting agents.", "tags": "", "url": "index.html#1.2604.vhahy.pg08x.5rww9.km6q6"},
     
     {"title": "Intro", "text": "Since then there has been good news on this front. In the 2016 AutumnStatement the Chancellor announced an intentionto ban fees charged to tenants.^0 This is a now anissue with cross party support - in the on-going general election theConservative Party, Labour Party, and Liberal Democrats have a commitment intheir manifestos to banning fees.", "tags": "", "url": "index.html#1.6866.fhfl9.g0cya.zujxt.9wg3p"},
     
     {"title": "Intro", "text": "The purpose of this update is to feed back into the live Department ofCommunities and Local Government (DCLG) consultation on letting fees andprovide the most up-to-date impression of letting fees. In addition to addingnew areas of coverage, we have revisited those areas and agents previouslyresearched in early 2016 to see how the picture of compliance and costs haschanged.", "tags": "", "url": "index.html#1.6854.vilsj.w5q7x.uexgj.fooi5"},
     
     {"title": "Intro", "text": "The Association of Residential Letting Agents (ARLA) have commissioned severalpieces of research in the effects of letting fees and argue against a ban.This update will address the issues raised by that research. In particular,arguing that an analysis showing a cost to long term tenants failed to takeinto account the effects the widespread practice of &quot;renewal fees&quot; have onannual costs to tenants - and the general distortion fees have on the smoothrunning of an efficient lettings market.", "tags": "", "url": "index.html#1.8507.kwuj8.l-vkx.7qupv.w3hhw"},
     
     
     
     {"title": "How have fees changed?", "text": "We have expanded our coverage to 1,087 agents across 20 councils. We have alsorevisited agents researched for the previous report to see how the picture offees (and accessibility to fees) has changed in the last year.", "tags": "", "url": "index.html#2.1871.nosa2.775ex.p9fu5.qac86"},
     
     {"title": "How have fees changed?", "text": "We now show an average fee of &amp;#163;404 for two tenants. This ranges from &amp;#163;40 to&amp;#163;813 for two tenants (ignoring those agents who charge no fees). Breakdowns ofthese fees can be seen in more detail at:http://lettingfees.co.uk/stats/", "tags": "", "url": "index.html#2.2319.x_gum.5xlak.2izf2.vg27b"},
     
     {"title": "How have fees changed?", "text": "We revisited the 742 agents that were on the system in mid-April 2016 to seehow the picture had changed over time. To make this comparison we madeadjustments to the old database to account for later corrections to modifiers(e.g. where we had a discount rate applying for the third rather than secondtenant, and vice versa) - this helps isolate changes in fees fromtranscription errors (although some fee changes will still represent errorcorrection rather than new fee schedules).", "tags": "", "url": "index.html#2.1485.shttq.a6idn.qlsxp.j6rx_"},
     
     {"title": "How have fees changed?", "text": "Looking at agents who had fees available in both periods (598) - we found 197(33%) with higher fees and 113 (19%) with lower fees. 48% of these agents sawno change in this year. While there is a slight average increase in fees(there is a &amp;#163;3 increase in the average between these two sets of agents) - thetwo sets cannot be statistically distinguished in a t-test because of thelarge number of agents who stayed the same. While more agents are now recordedwith higher fees, this average increase (&amp;#163;79.6) was less than the averagechange in the fewer agents now recorded with decreased fees (-&amp;#163;125). Theincrease in the average fee across our database from our initial reportresults more from improved handling of discount rates and new additions thanan increase in fees in the original agents.", "tags": "", "url": "index.html#2.2265.joqe0.p4l4w.xgkhj.rgzwk"},
     
     {"title": "How have fees changed?", "text": "In terms of compliance, 40 of our 100 letting agents that were previously notcompliant now displayed their fees. There were 10 agents who previouslydisplayed fees for whom we can no longer find listed fees. There were alsoinstances where comprehensive fees pages had been replaced by abridgedcomments in the listing description. In these instances we would remove theadditional fees we had in the system as we could no longer find sources.", "tags": "", "url": "index.html#2.7354.ccvwj.ia_pc.ebizn.nkqf2"},
     
     {"title": "How have fees changed?", "text": "Compliance as a whole in our dataset is up (from 87% to 88%) - but thisreflects a survivorship bias as agents who were non-compliant were more likelyto leave the market. 16% of agents who did not list fees appeared to havestopped trading, as opposed to 3% of those who previously had. In areas wherewe looked for new agents we tended to find new non-compliant agents to replacethose that had previously gone out of business. We did not search for newagents in all areas, so our compliance statistics are now generous in someareas due to this effect.", "tags": "", "url": "index.html#2.1316.bxwck.apcus.noe7k.pqzhy"},
     
     
     
     {"title": "ARLA Research", "text": "ARLA have commissioned two pieces of research into the ban of letting fees.One isa survey of letting agentsconducted by Opinium to determine servicescharged for and the work and time involved in providing them.^0 The other wasananalysis by Capital Economicsinto the likely effects on the lettings marketof a ban.^1", "tags": "", "url": "index.html#3.5327.943cv.egkog.jekjj.5scw-"},
     
     {"title": "ARLA Research", "text": "Neither report particularly disputes that letting fees are expensive. TheOpinium research is notable for not asking at all what price agents werecharging for these services and for combining &amp;#8216;tenancy agreements / renewals&#39;into a single item (which obfuscates how many letting agents charge tenantsannually - which as we&#39;ll explore would be a useful number to know). TheCapital Economics report did not contest that letting fees were a substantialcost to tenants (in fact we were happy to see that they took lettingfees.co.ukstatistics as the best available measure of the current cost of letting fees),but instead argued that in the most likely scenario, letting agents andlandlords will absorb some of the cost but that there will be a rent increaseto tenants (but that for the most part this cost would be less than thesaving). They also argue that a ban would have an adverse effect on long-termtenants - who would see less of a benefit from a ban on fees while more costsas a result of rent rises.", "tags": "", "url": "index.html#3.2153.602wo.lomsn.dl8uk.uqv-_"},
     
     {"title": "ARLA Research", "text": "The effect of the Opinium report is to convey that letting agents work harddoing real work and that tenants are annoying (example quotes:&quot;Some peopletake longer than others especially when we&#39;re dealing with people overseas andpeople with complicated employment arrangements&quot;, &quot;Tenants constantly callasking for further information or information they have already beensupplied&quot;). They found that letting agents spent a surprisingly long time onitems they charge to tenants, including an average of eight hours on referencechecks and five hours finalising tenancy agreements^0. If we take the Opiniumstatistics at face value (ignoring that surveying letting agents on theeffects of losing an income stream might encourage exaggeration) it is anindictment of the state of the lettings market that theaveragetime spendon these tasks is so high. If half of letting agents take more than five hoursto prepare a tenancy agreement this getsat exactly the market problem we&#39;vebeen complaining about: why are these inefficient agents not being forced fromthe market and replaced by their more efficient competitors? The answer isthat the cost of their inefficiency (both in terms of time-wasted and in beingcharged for agent inefficiency) falls on tenants - who can do little aboutthis.", "tags": "", "url": "index.html#3.2960.akoby.cpyno.lc55f.m8-mg"},
     
     {"title": "ARLA Research", "text": "That letting agents&#39; work is real is not in dispute - what is in dispute iswho should pay for it. Tenants have no power to avoid or punish letting agentswho charge extortionate fees (or take far too long to perform basic tasks) orreward letting agents who run efficient businesses with their custom. This canonly be achieved by shifting all of the payment to the party with greatermarket power: the landlord.", "tags": "", "url": "index.html#3.4329.k5h2h.oduti.ti7vl.nu7ri"},
     
     {"title": "ARLA Research", "text": "The Capital Economics report deserves more consideration because they make agood-faith attempt to calculate what increase in rent might be expected -calculating an increase of &amp;#163;103 p/a as a likely result. They note that &quot;asrents will increase by less than the average tenant fees this will be positivefor tenants&quot; but then go on to say: &quot;However, those that move property lessoften will not reap the same benefits in savings. Typically, these are likelyto be lower income families who will probably move less often than younger,wealthier millennials.&quot;^1", "tags": "", "url": "index.html#3.8390.gbwx4.gts6m.aupev.f4kur"},
     
     {"title": "ARLA Research", "text": "That there is a point where this logically must be true our calculations findthe Capital Economics figures to be too pessimistic, with both larger savingsfor short-term tenancies and that a positive effect exists for longertenancies. Their report includes this table^0 showing the effects of a ban -finding that by five years tenants are paying more through increased rent thanthey are gaining through savings.", "tags": "", "url": "index.html#3.6098.alqqx.dibup.8koyo.yb98m"},
     
     {"title": "ARLA Research", "text": "asset:their-graph", "tags": "", "url": "index.html#3.158.ladws.8jpr8.f31-l.2jmj7"},
     
     {"title": "ARLA Research", "text": "There is an obvious problem here - despite Capital Economics accepting afigure of &amp;#163;412 from lettingfees.co.uk (March 2017) as a reasonable figure forthe cost due to fees of moving, this chart says someone who only moves once inten years is saving only &amp;#163;275. The explanation for this error is that they usethe annualised cost to the letting agent of a fees ban (&amp;#163;412 over an averagetenancy of 1.5 years == &amp;#163;274.66) as the saving each time someone moves. Forexample, to reach a saving of &amp;#163;5,493 for a pair or tenants who move every sixmonths (twenty times in ten years) they multiple &amp;#163;274.66 by 20. This isincorrect - they need to multiply &amp;#163;412 by 20 - which gives a saving in feesnot paid of &amp;#163;8,230 if a tenant moves every six months. As their proposed rentincrease is derived from the average fee, this would undercount the benefitto tenants no matter what figure for average letting fees was used.", "tags": "", "url": "index.html#3.2772.hkoj2.tno--.6lwsx.hd3p7"},
     
     {"title": "ARLA Research", "text": "While reducing the scale of their argument this still shows tenants in longertenancies are losing money; but there is a more fundamental problem with thisanalysis - it lacks an understanding of the role of renewal fees in thelettings market.", "tags": "", "url": "index.html#3.1481.tvmft.1u7ti.7qupv.9qebx"},
     
     {"title": "ARLA Research", "text": "In our previous reportwe coveredthe perverse incentive fees create toencourage churn in tenancies. A Department for Communities and Local Government (DCLG) report noted that &quot;unscrupulous&quot; agentscan &quot;frustrate landlords and tenants by generating an unnecessary churn ofcontracts to extract new tenant fees&quot;.^1 Renewal fees blunt this incentiveby effectively buying off letting agents - tenants pay a sum to continue inthe same property on the same contract. This is strictly speaking unnecessaryand the Competition and Marketing Authority caution against agents giving the&quot;impression that the tenant is obliged to agree to a new fixed termagreement&quot;.^2 In reality, the ever-present threat of eviction can be used toextract money every year (or for the unlucky, every six months) from thetenant.", "tags": "", "url": "index.html#3.8726.f4bpw.i3dew.yi2ys.xno6s"},
     
     {"title": "ARLA Research", "text": "While Capital Economics assume that letting agents only apply upfront costs totenants, for those with letting agents charging renewal fees there areadditional annual costs. As previously mentioned, Opinium have failed to giveus a useful number for how many agents charge renewal fees - so we will haveto extrapolate from the lettingfees.co.uk database.", "tags": "", "url": "index.html#3.8111.qyxd6.zwtfi.vhrnd.c22zr"},
     
     {"title": "ARLA Research", "text": "The average renewal fee in the database is &amp;#163;117 and this is charged by 609agents. As not all agents charge renewal fees we will adjust this downwards bya ratio of 609:1045 (representing all agents in the database who display feesand charge fees). Assuming annual tenancies, this gives us an average cost of&amp;#163;68.18. As a tenant who moves every six months will never pay renewal fees(and so saves nothing from their ban) - accounting for this fee benefits longterm tenants more than short term tenants. This amended table shows how thisaffects net gains: not only are the average savings to tenants in shortertenancies higher as a result of using the correct figure for tenant fees - butaccounting for renewal fees gives a net benefit at five years, and a net lossof only &amp;#163;4 at ten years.", "tags": "", "url": "index.html#3.8074.9kzji.vpies.6ps9p.ik_cm"},
     
     {"title": "ARLA Research", "text": "asset:our-graph", "tags": "", "url": "index.html#3.8277.wdeov.xyv8w.xk2nc.2jmj7"},
     
     {"title": "ARLA Research", "text": "Being as precise as &amp;#8216;losing &amp;#163;4 over ten years&#39; reflects the problems of thisexercise. Some long term tenants are not charged renewal fees and so will seeless benefit - but among those that are currently charged the fee is likely tobe greater than &amp;#163;68 - and so they will receive more benefit. Rent increases remainhypothetical, if they materialise they will interact with conditions of thehousing market in different areas to lead to different rises in differentplaces.  This analysis presents an average picture - but it is useful simply tosay that the data does not say that a tenant fee ban benefits the young andrich over the old and poor.", "tags": "", "url": "index.html#3.7461.vie0e.apbh2.aztfn.px4zf"},
     
     {"title": "ARLA Research", "text": "It is worth remembering that most tenancies are short. The majority, 59.5% areunder three years, with 76.5% under five.^0 While long term tenants benefit lessfrom a ban on initial fees, they benefit more from the effect on renewal feesand in aggregate there is a net benefit even for relatively long tenancies.", "tags": "", "url": "index.html#3.9507.-ipkv.0hipx.thwpa.erhwo"},
     
     
     
     {"title": "Distorting Effects", "text": "The Capital Economics report argues that poorer tenants are less likely tomove, and so are less affected by fees - but for some of these tenants thecost of fees is part of the reason why they can&#39;t move. In our original reportwe argue for a ban on the basis that distributing the cost over the length ofa tenancy is good for tenants as it makes payments more manageable. If tenantsdo not have the savings required to pay the upfront costs of moving, they aretrapped in their current property.", "tags": "", "url": "index.html#4.7951.h08dx.gts6m.p0fmb.yi7nk"},
     
     {"title": "Distorting Effects", "text": "The presence of fees can have a negative effect even if never charged. In thiswave of research we found an agent who was charging a &amp;#8216;Deposit DisputeAdministration&#39; of &amp;#163;120. This caught our researcher&#39;s attention because theypersonally had a letting agent in 2014 who sent a end of tenancy letter sayingthat: &quot;In the event of a dispute and a DVD recording is required as evidencefor the deposit protection service, you will be held liable for this cost @75.00 + VAT&quot;.^0 That letting agent now does make their fees public, and doesn&#39;tmention this fee - so they may have stopped charging it. But seeing whatseems like a version of that fee in public hints that there may be others likethat out there. Not only are there agents that charge for deposit protection(which is a free service unless a letting agent wants to hold the depositthemselves and run their business using the money - so charging for this isthe equivalent of charging someone giving you an interest-free loan) but thereare some who threaten fees to tenants who want to exercise their right to usethis service.", "tags": "", "url": "index.html#4.2581.6gl04.u1d_h.avhbo.xqdnp"},
     
     {"title": "Distorting Effects", "text": "This example reflects that fees aren&#39;t only harmful when they&#39;re charged,they&#39;re harmful because of what they stop happening. Someone who accepts anunjustified &amp;#163;90 deduction from their deposit because the cost of disputing itis the same is financially punished by a fee, even if it&#39;s never charged.People who avoid moving because the fixed costs of moving is so great are hurtby letting fees even when they&#39;re not charged them. Letting fees cannot beviewed as simply costs, they have a distorting effect on the letting market -keeping people less mobile than they might otherwise be and creatingincentives for agents to work against the best interests of both landlords andtenants.", "tags": "", "url": "index.html#4.8513.apw8q.5isnu.lnmlx.sgy3u"},
     
     {"title": "Distorting Effects", "text": "Lowering the cost of moving and ensuring renters are able to exercise theirrights freely by banning fees does not hurt poorer renters at the expense ofwealthier ones - it creates a more fair lettings market for all.", "tags": "", "url": "index.html#4.4881.lmlsj.oveqo.1z6v8.11i38"},
     
     
     
     {"title": "Exceptions", "text": "The lettings industry would like to carve out an exception for referencing.^0 The belief that tenants should pay for this is the result of a general confusion in the industry about what it means to provide a service. For instance, the Capital Economics report argues that:&quot;Fees are charged to tenants to reflect real work that is undertaken on behalf of them, including checking references, drawing up tenancy agreements, conducting credit checks and general administration&quot;.", "tags": "", "url": "index.html#5.7564.xgjny.9vwim.rx9xf.tdih0"},
     
     {"title": "Exceptions", "text": "The key problem here is that credit checks and checking references are notactivities done on behalf of the tenant. A good tenant gains nothing throughbeing referenced, and a bad tenant would lose out through being referenced.Referencing is not a service to the tenant, it is a service to the landlord tosecure against rental income loss (which is why the more expensive third-partyreferencing services also offer rental insurance as part of the package).", "tags": "", "url": "index.html#5.5655.59wta.-3tff.c3rhk.uctl0"},
     
     {"title": "Exceptions", "text": "Letting agents have fallen into the pattern of assuming whenever they aretalking to a tenant they are providing a service - but in many cases they areacting as the landlord&#39;s agent in the relationship with the tenant. Eitherreferencing is a useful tool to reduce risk to landlords (in which case theyshould be happy to have it included as part of their fees) - or it isn&#39;t andtenants are being charged for no reason.", "tags": "", "url": "index.html#5.4309.1dtpw.yajs9.yrsw-.ksrq6"},
     
     {"title": "Exceptions", "text": "A reasonableargumentforretaining fees for referencing is that tenants need &quot;skin in the game&quot; toavoid people submitting for references they are likely to fail - but thisrequirement is met by holding deposits. Pleading at this point that certainfees need to be preserved might find a more sympathetic audience if theindustry had shown restraint to date. The average fee charged to two peoplefor referencing alone is &amp;#163;155. This is an incredible mark-up from third-partyservices that charge &amp;#163;40-80 for two tenants. Letting agents have had a chanceto charge a reasonable deterrence fee - and the overwhelming majority havechosen not to do that. It is not credible that if allowed to retain anyability to set fees the industry will show restraint.", "tags": "", "url": "index.html#5.3656.jajlo.d-wdl.ywd5x.3bxmd"},
     
     
     
     {"title": "A Better Lettings Market", "text": "While it is natural that ARLA would attempt to marshal arguments in theinterests of its members, the industry as a whole should reflect on thebehaviour that has brought them to this point. It is to the benefit of hard-working and efficient letting agents that the true costs of their competitorsare exposed to landlords - who will be able to make better decisions as towhich agent to trust with their property. If agents who currently can undercuton landlord fees through heavy charges to tenants can no longer do so,competition becomes fairer. Letting agents who can proceed a reference inunder eight hours should consider how long they want to be tarred with thesame brush as their competitors.", "tags": "", "url": "index.html#6.4312.2gmbl.e5i24.sd4yv.j_o7t"},
     
     {"title": "A Better Lettings Market", "text": "Report Author: Alex Parsons. With thanks again to the lettingfees.co.uk volunteers.", "tags": "", "url": "index.html#6.3151.8awyv.0qr6q.c9ley.bhwu9"}
     
     
]};